"""Add timestamps to WorkflowInstance

Revision ID: 39fd3adbb441
Revises: aa0291d2f2df
Create Date: 2025-11-20 23:12:42.504077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fd3adbb441'
down_revision: Union[str, Sequence[str], None] = 'aa0291d2f2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_instances', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workflow_instances', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_instances', 'updated_at')
    op.drop_column('workflow_instances', 'created_at')
    # ### end Alembic commands ###
