"""Make instance_id nullable in Attachment and fix timestamps

Revision ID: 4b4e7ca76fed
Revises: aa0291d2f2df
Create Date: 2025-11-21 23:53:56.086106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4e7ca76fed'
down_revision: Union[str, Sequence[str], None] = 'aa0291d2f2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'instance_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('workflow_instances', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workflow_instances', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_instances', 'updated_at')
    op.drop_column('workflow_instances', 'created_at')
    op.alter_column('attachments', 'instance_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
